version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3366:3306"
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rails_app_db

volumes:
  db-volume: